package io.mosn.coder.intellij.util;

public class CodeBuilder {

    private StringBuilder buff;

    public CodeBuilder(StringBuilder buff) {
        this.buff = buff;
    }

    public CodeBuilder header() {
        this.buff.append("/**\n")
                .append("* Generated by mosn mecha\n")
                .append(" */\n");
        return this;
    }

    public CodeBuilder with(String line) {
        this.buff.append(line);
        return this;
    }

    public CodeBuilder append(String line) {
        return append(line, true);
    }

    public CodeBuilder append2(String line) {
        return append(line, true).line();
    }

    public CodeBuilder append(String line, boolean newLine) {
        this.buff.append(line);
        if (newLine) {
            this.buff.append("\n");
        }
        return this;
    }

    public CodeBuilder line() {
        this.buff.append("\n");
        return this;
    }

    public CodeBuilder line(int num) {
        if (num > 0 && num < 10) {
            while (num-- > 0) {
                this.buff.append("\n");
            }
        }

        return this;
    }

    @Override
    public String toString() {
        return this.buff.toString();
    }
}
